os: linux

language: generic

dist: xenial

services:
  - docker

branches:
  only:
    - master

# test 이미지 빌드
before_install:
  - docker build -t chane81/react-test-app -f ./frontend/Dockerfile.dev ./frontend

# react 테스트
script:
  - docker run -e CI=true chane81/react-test-app npm run test -- --coverage

# 이미지 빌드
after_success:
  - echo "Test Success"
  - docker build -t chane81/docker-frontend ./frontend
  - docker build -t chane81/docker-backend ./backend
  - docker build -t chane81/docker-nginx  ./nginx

  # docker hub 로그인
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  # 이미지들 hub에 push
  - docker push chane81/docker-frontend
  - docker push chane81/docker-backend
  - docker push chane81/docker-nginx

# 배포
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-611302950754"
  bucket_path: "docker-fullstack-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY